# Generated by Django 5.1.4 on 2025-02-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authub', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
    ]
