# Generated by Django 5.1.4 on 2025-02-19 10:14

import dietitians.enum
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Dietitian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('full_name', models.CharField(max_length=255)),
                ('licence_number', models.CharField(max_length=50, unique=True)),
                ('diploma', models.FileField(blank=True, null=True, upload_to='diploma/')),
                ('experience_years', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('expertise_fields', models.PositiveSmallIntegerField(blank=True, verbose_name=dietitians.enum.ExpertiseField)),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Approved'), (3, 'Rejected')], default=1)),
                ('gender', models.PositiveSmallIntegerField(choices=[(1, 'Male'), (2, 'Female'), (3, 'Other')])),
                ('location', models.CharField(max_length=255)),
                ('website', models.URLField(blank=True, null=True)),
                ('social_media', models.JSONField(blank=True, null=True)),
                ('references', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dietitian_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Dietitian',
                'verbose_name_plural': 'Dietitians',
            },
        ),
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='certifications/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('dietitian', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certifications', to='dietitians.dietitian')),
            ],
        ),
    ]
