# Generated by Django 5.1.4 on 2025-02-19 12:22

import dietitians.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitians', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dietitian',
            name='username',
            field=models.CharField(default=1, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='certification',
            name='file',
            field=models.FileField(upload_to=dietitians.models.dietitian_directory_path),
        ),
        migrations.AlterField(
            model_name='dietitian',
            name='diploma',
            field=models.FileField(blank=True, null=True, upload_to=dietitians.models.dietitian_directory_path),
        ),
        migrations.AlterField(
            model_name='dietitian',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
