# Generated by Django 5.1.4 on 2025-02-20 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dietitians', '0002_dietitian_username_alter_certification_file_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dietitian',
            old_name='full_name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='dietitian',
            name='last_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dietitian',
            name='title',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
